spring:
  application:
    name: product-api

  datasource:
    url: ${DB_HOST:jdbc:postgresql://localhost:5434/mydb}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:secret123}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8383
springdoc:
  swagger-ui:
    path: /product/swagger-ui/index.html
  api-docs:
    path: /product/v3/api-docs
