server:
  port: ${SERVER_PORT:8282}

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/api/v1/products/**
              filters:
                - StripPrefix=0
            - id: product-service-swagger-ui
              uri: lb://product-service
              predicates:
                - Path=/product/swagger-ui/**,/product/swagger-ui.html,/product/swagger-ui/index.html
            - id: product-service-openapi
              uri: lb://product-service
              predicates:
                - Path=/product/v3/api-docs/**
            - id: product-service-openapi-root
              uri: lb://product-service
              predicates:
                - Path=/product/v3/api-docs

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    path: /swagger-ui/index.html
    disable-swagger-default-url: true
    urlsPrimaryName: product-service
    urls:
      - name: product-service
        url: /product/v3/api-docs
